### PR TITLE
Add quote from Connor Leahy

### PR DESCRIPTION
**Pull request by mrbreastly**
It should looks like this when it's merged...

image

### CODE REVIEW

**Comment by mrbreastly** [comment]
Ok, I fixed the conflict with the previous quote PR.  Good to go now.
I tested it locally.  It should looks like this when it's merged... 
image

**Comment by Pato-desu** [comment]
I would merge it, but I wonder about the rights of the image. Do you know about it? I'm sure you read about it in the other PR

**Comment by Pato-desu** [comment]
and you should do the same with the Paul and Jaan quotes

**Comment by mrbreastly** [comment]
> I would merge it, but I wonder about the rights of the image. Do you know about it? I'm sure you read about it in the other PR

It's a screenshot from the youtube video from where there quote is take from the youtube video ...
https://www.youtube.com/watch?v=52V5dOQVDy8

The video is on the Cambridge Union which links to https://cus.org.
So, I added those into the Copyright attribution field... 
```    "notice": "© Cambridge Union, https://cus.org"```

**Pull request merged**
