### PR TITLE
Environmental draft Remmelt

### PR DESCRIPTION
**Pull request by joepio**
Written by Remmelt Ellen.

I'd love to hear some feedback about this page. It introduces a new risk and a new angle.

### CODE REVIEW

**Comment by Pato-desu** [comment]
Well, personally I like it for the most part but not the last sections, which I understand is what Remmelt would like to put the most.

When I wrote most sections of the /risks page, I try to look about the effects of AI on the climate and I didn't put it because I didn't find much and didn't feel comfortable written about something I didn't knew. Also considering that there's a lot of things that are hard to calculate, and narrow AI could bring pros on the environment which makes it net positive.

But I'm happy that Emmelt wrote about it and put sources. After reading the costs on the environment I feel more confident calling it a risk. 

But the last 2/3 sections read like the "disempowerment" and "x-risk" section again, and I think this page should exist mainly to convince climate activists. I feel like people who believe we could just turn-off the machines on the long run worry about not realizing it before too much damage has been done, not self-replicating machines.

P.D: I also kinda hate the video linked.

**Comment by joepio** [comment]
> narrow AI could bring pros on the environment, AIs could end up being net positive for the environment.

I can see how AI might help in material science for a fusion reactor, for example, so I agree that there is a chance this all works out. But it depends on more assumptions than just "more AI = more compute used = more emissions", right?

> But the last 2/3 sections read like the "disempowerment" and "x-risk" section of /risks again, and I think this page should exist mainly to convince climate activists. I feel like people who believe we could just turn-off the machines on the long run worry about not realizing it before too much damage has been done, not self-replicating machines.

I think you're right. We'll probably lose some readers here who would otherwise be sympathetic.

**Comment by joepio** [comment]
Removed the last part as per Remmelt's request

**Comment by Pato-desu** [comment]
Which part did you removed @joepio ? Isn't the version live the original text?

**Pull request merged**
